language: node_js
node_js:
  - "0.12"
sudo: false
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
env:
  global:
    - secure: h+TWhc63hT5AU6qTg041eUMDKbY73zhYlPjXqaOrqK0D8QXvG34KPz8f5mBMluY7XKV/vwPpjg+aV7qInJP+dYmktNqIsxhhoVet4ywXN9D5h9g8v3jNRpkK+ISnWGdyeAzwCjYCo14p+hwiypPP4hGTX1X+YDR07rfLsIjQOjU=
    - secure: S6E5M3mgWc7LnFdypycWMgQsvSF7Ez55nD94CdAhRSEpmrb+A6SgmBbTmwBxLgGcgKdo5itngLifGi9MZ3kjDs6WwQfgzX1iVIzDitzSOSyTUtXLYLTVkOU888IixRrpIlunXp5ZbJCnZxKCjvVmMGIQsAQjMmBxumUI5DO74yM=
