language: node_js
node_js:
  - "0.12"
sudo: false
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
env:
  global:
    - secure: gaafQQ+jampaDIR783GrfBLehLqmwFZiWtfQzXVmpoya9BON48XBFBWSEKl7dyMVK/6zMPV1HQGi6B5u8X7bYsWoY8CBW+YxEw1yBYcVp9yQzQayp+ZtBo/D2R/PnjscoPL5UmJZqNem9ha9wr5Qcf2n/jfBlxt76Z2ph/px+xY=
    - secure: CwEz1yVqZ6MGJh0J4P1c/k6+kejPKw+0duWGW5OlE89uB+rfqVQo15jn/yw6jbafAGEj37/eOrp81Kb/Q8iWuafSE1nQKwP+kP3lwVyKfjOm6nCO7fnYIvLZGQHGgu1k0puon5vMpcE9WCRnBKcl/rhIlwG8fXHVeDt16bvBrRM=
